AWSTemplateFormatVersion: 2010-09-09
Description: TestTask stack
Parameters:
  ImageId:
    Description: ImageId to use
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2
Resources: 
  TestTaskVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.110.110.0/24
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: TestTaskVpc

  TestTaskIgw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: name
          Value: TestTaskIgw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref TestTaskVPC
      InternetGatewayId: !Ref TestTaskIgw

  TestTaskSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, Fn::GetAZs: !Ref "AWS::Region"]
      VpcId: !Ref TestTaskVPC
      CidrBlock: 10.110.110.0/24
      Tags:
        - Key: Name
          Value: TestTaskSubnet
      MapPublicIpOnLaunch: true
  
  TestTaskRt:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref TestTaskVPC
      Tags:
        - Key: Name
          Value: TestTaskRt
  
  TestTaskRtAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TestTaskSubnet
      RouteTableId: !Ref TestTaskRt

  TestTaskRtDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref TestTaskRt
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref TestTaskIgw
  
  TestTaskENI:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: "TestTask Instance ENI"
      SourceDestCheck: false
      SubnetId: !Ref TestTaskSubnet
      Tags:
        - Key: Name
          Value: TestTaskENI

  TestTaskInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      IamInstanceProfile: !Ref Ec2InstanceProfile
      InstanceType: t4g.small
      Monitoring: false
      Tags:
        - Key: Name
          Value: TestTaskInstance
      NetworkInterfaces:
      - NetworkInterfaceId: !Ref TestTaskENI
        DeviceIndex: 0
      UserData: "IyEvdXNyL2Jpbi9lbnYgYmFzaAp5dW0gaW5zdGFsbCBnaXQgLXkKZ2l0IGNsb25lIGh0dHBzOi8vZ2l0aHViLmNvbS9WZXJvbmNoZWcvVGVzdFRhc2sxLmdpdCAKY2QgVGVzdFRhc2sxCmNwIHRlc3Rsb2cuc2VydmljZSAvZXRjL3N5c3RlbWQvc3lzdGVtLwpjcCB0ZXN0bG9nLnNoIC91c3IvYmluLwpjcCB0ZXN0bG9nIC92YXIvbG9nLwpzeXN0ZW1jdGwgZGFlbW9uLXJlbG9hZApzeXN0ZW1jdGwgZW5hYmxlIHRlc3Rsb2cuc2VydmljZQpzeXN0ZW1jdGwgc3RhcnQgdGVzdGxvZy5zZXJ2aWNlCg=="
  
  IamRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "TestTaskEc2RoleForSSM"
      Description: "EC2 IAM role for SSM access"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"

  Ec2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: "TestTaskEc2RoleForSSM"
      Roles:
        - Ref: "IamRole"
